# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
        ('Section', '0001_initial'),
        ('Batch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=120)),
                ('middle_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=20)),
                ('blood_group', models.CharField(choices=[('Unknown', 'Unknown'), ('A+ve', 'A+ve'), ('A-ve', 'A-ve'), ('B+ve', 'B+ve'), ('B-ve', 'B-ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve'), ('O+ve', 'O+ve'), ('O-ve', 'O-ve')], default='Unknown', max_length=20)),
                ('birth_place', models.CharField(max_length=120, null=True)),
                ('nationality', models.CharField(default='Nepal', max_length=120)),
                ('mother_tongue', models.CharField(max_length=40, null=True)),
                ('religion', models.CharField(max_length=60)),
                ('permanent_address', models.CharField(blank=True, max_length=60, null=True)),
                ('temporary_address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('state', models.CharField(blank=True, max_length=60, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=60, null=True)),
                ('Country', models.CharField(default='Nepal', max_length=60)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Batch.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Section.Section')),
            ],
        ),
    ]
