# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '__first__'),
        ('Batch', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Batch.Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
